VERILOG = ../src/atari_2600.v ../src/tia.v ../src/pia.v \
	  ../src/memory/ram.v ../src/memory/dprom.v ../src/memory/dpram.v \
	  ../src/cpu/chip_6502.v ../src/cpu/chip_6502_mux.v \
          ../src/lattice/ecp5pll.sv \
          ../src/spi_display/lcd_video.v \
	  ../src/pot/quad.v \
	  ../src/match.v ../src/detect.v \
          ../src/spi_display/hex_decoder_v.v \
	  ../src/osd/osd.v ../src/osd/spi_osd.v ../src/osd/spi_ram_btn.v \
	  ../src/osd/spirw_slave_v.v \
	  ../src/video/hdmi.v ../src/video/video.v

PIN_DEF = ulx3s_v20.lpf
DEVICE = 12k
include ulx3s.mk

